### ISSUE TITLE
probably an npm thing but missing dep error

### ISSUE THREAD

**Issue by the1mills** [isaacs/inflight#6]
I saw this error after an npm install:

```
Error: Cannot find module 'wrappy'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/oleg/codes/sce/suman-chrome-extension/node_modules/inflight/inflight.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

```

Here is the package.json for inflight:

```
{
  "_args": [
    [
      "inflight@1.0.6",
      "/home/oleg/codes/sce/suman-chrome-extension"
    ]
  ],
  "_development": true,
  "_from": "inflight@1.0.6",
  "_id": "inflight@1.0.6",
  "_inBundle": false,
  "_integrity": "sha1-Sb1jMdfQLQwJvJEKEHW6gWW1bfk=",
  "_location": "/inflight",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "inflight@1.0.6",
    "name": "inflight",
    "escapedName": "inflight",
    "rawSpec": "1.0.6",
    "saveSpec": null,
    "fetchSpec": "1.0.6"
  },
  "_requiredBy": [
    "/glob",
    "/glob-stream/glob",
    "/stylus/glob",
    "/true-case-path/glob"
  ],
  "_resolved": "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz",
  "_spec": "1.0.6",
  "_where": "/home/oleg/codes/sce/suman-chrome-extension",
  "author": {
    "name": "Isaac Z. Schlueter",
    "email": "i@izs.me",
    "url": "http://blog.izs.me/"
  },
  "bugs": {
    "url": "https://github.com/isaacs/inflight/issues"
  },
  "dependencies": {
    "once": "^1.3.0",
    "wrappy": "1"
  },
  "description": "Add callbacks to requests in flight to avoid async duplication",
  "devDependencies": {
    "tap": "^7.1.2"
  },
  "files": [
    "inflight.js"
  ],
  "homepage": "https://github.com/isaacs/inflight",
  "license": "ISC",
  "main": "inflight.js",
  "name": "inflight",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/npm/inflight.git"
  },
  "scripts": {
    "test": "tap test.js --100"
  },
  "version": "1.0.6"
}

```

**Comment by isaacs** [comment]
https://github.com/isaacs/inflight/issues/5#issuecomment-2126153820
